{
  "formatVersion": "1.1",
  "component": {
    "group": "frc4068.bearlib",
    "module": "bearlib",
    "version": "2025.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "bearlib-2025.1.0.jar",
          "url": "bearlib-2025.1.0.jar",
          "size": 38828,
          "sha512": "173710adbcd6c9b6c7533c9402694292892f0341de818aa74776a697bf62f94b5f35b841ff4afc4ae88307d533d9f9bcf10f399995524844cd7392e31df7842d",
          "sha256": "794d845994987fe14a1ff0211d5fa9804052db20e73692fbc03816a5af35c1fb",
          "sha1": "a0285f61baf633c6586213228b8d31311f37814c",
          "md5": "c6869224004a97b2487ceb58fdacd96c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2025.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2025.1.1"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2025.1.1"
          }
        },
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2025.1.1"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2025.1.1"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2025.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpinet",
          "module": "wpinet-java",
          "version": {
            "requires": "2025.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2025.1.1"
          }
        },
        {
          "group": "edu.wpi.first.apriltag",
          "module": "apriltag-java",
          "version": {
            "requires": "2025.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiunits",
          "module": "wpiunits-java",
          "version": {
            "requires": "2025.1.1"
          }
        },
        {
          "group": "edu.wpi.first.epilogue",
          "module": "epilogue-runtime-java",
          "version": {
            "requires": "2025.1.1"
          }
        },
        {
          "group": "edu.wpi.first.thirdparty.frc2025.opencv",
          "module": "opencv-java",
          "version": {
            "requires": "4.10.0-3"
          }
        },
        {
          "group": "org.ejml",
          "module": "ejml-simple",
          "version": {
            "requires": "0.43.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.15.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.15.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.15.2"
          }
        },
        {
          "group": "us.hebi.quickbuf",
          "module": "quickbuf-runtime",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "edu.wpi.first.wpilibNewCommands",
          "module": "wpilibNewCommands-java",
          "version": {
            "requires": "2025.1.1"
          }
        },
        {
          "group": "com.revrobotics.frc",
          "module": "REVLib-java",
          "version": {
            "requires": "2025.0.0"
          }
        },
        {
          "group": "gov.nist.math",
          "module": "jama",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.18.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jdk8",
          "version": {
            "requires": "2.15.2"
          }
        }
      ],
      "files": [
        {
          "name": "bearlib-2025.1.0.jar",
          "url": "bearlib-2025.1.0.jar",
          "size": 38828,
          "sha512": "173710adbcd6c9b6c7533c9402694292892f0341de818aa74776a697bf62f94b5f35b841ff4afc4ae88307d533d9f9bcf10f399995524844cd7392e31df7842d",
          "sha256": "794d845994987fe14a1ff0211d5fa9804052db20e73692fbc03816a5af35c1fb",
          "sha1": "a0285f61baf633c6586213228b8d31311f37814c",
          "md5": "c6869224004a97b2487ceb58fdacd96c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "bearlib-2025.1.0-sources.jar",
          "url": "bearlib-2025.1.0-sources.jar",
          "size": 28010,
          "sha512": "f21ac9292f2c2fe6ded5cf21b62854e0350bee883fc20418444b2498c5b5756a1e531366eff688660a5c5632c8c393d41b4555f51c823661be735185c2476d90",
          "sha256": "069a8eac6ea0c31b6e268851b1a440763ab1f660f6a6ee300c8bb7c208dfb216",
          "sha1": "b13eb5d5f14c124188236f02ec114253f97e27dc",
          "md5": "bb4651e938802a272f76ad68f57fb788"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "bearlib-2025.1.0-javadoc.jar",
          "url": "bearlib-2025.1.0-javadoc.jar",
          "size": 223892,
          "sha512": "e07a8c3809dcde0be4708ec67333f708258365f6647ccb518d63b3e2c1a9caf1398a24082bdaab5f1f6f751405ad7b114e3f1268ad284a0255628ba6fab52efa",
          "sha256": "e0cc558e97813be953dab51b919465c0a280764eb2a131afae8bdbfaee366e2a",
          "sha1": "48329bd57658ac273e6c2c668da96b5674bdf392",
          "md5": "c77df0b643dab75c4a382ceba3c606cd"
        }
      ]
    }
  ]
}
