{
  "formatVersion": "1.1",
  "component": {
    "group": "frc4068.bearlib",
    "module": "bearlib",
    "version": "2025.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "bearlib-2025.0.2.jar",
          "url": "bearlib-2025.0.2.jar",
          "size": 18836,
          "sha512": "79e5b45eaa5979ecfa6f84e1476ff9d1c299ddc2ff4cf4d5f1dc3f0a428881d24a156cca217d399220062ac27bff07cc2e815da4a3cb7ab00dab9ac3a0b3473d",
          "sha256": "7a4fdd2223ec2b51c9facda767a6c2ac1cab15e541627a0a8dead2fc20bb40eb",
          "sha1": "3585039616268f9f995ffde92557524e865cff14",
          "md5": "a80d97f932ef08f02161663805f718c6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2025.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2025.1.1"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2025.1.1"
          }
        },
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2025.1.1"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2025.1.1"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2025.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpinet",
          "module": "wpinet-java",
          "version": {
            "requires": "2025.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2025.1.1"
          }
        },
        {
          "group": "edu.wpi.first.apriltag",
          "module": "apriltag-java",
          "version": {
            "requires": "2025.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiunits",
          "module": "wpiunits-java",
          "version": {
            "requires": "2025.1.1"
          }
        },
        {
          "group": "edu.wpi.first.epilogue",
          "module": "epilogue-runtime-java",
          "version": {
            "requires": "2025.1.1"
          }
        },
        {
          "group": "edu.wpi.first.thirdparty.frc2025.opencv",
          "module": "opencv-java",
          "version": {
            "requires": "4.10.0-3"
          }
        },
        {
          "group": "org.ejml",
          "module": "ejml-simple",
          "version": {
            "requires": "0.43.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.15.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.15.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.15.2"
          }
        },
        {
          "group": "us.hebi.quickbuf",
          "module": "quickbuf-runtime",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "edu.wpi.first.wpilibNewCommands",
          "module": "wpilibNewCommands-java",
          "version": {
            "requires": "2025.1.1"
          }
        },
        {
          "group": "com.revrobotics.frc",
          "module": "REVLib-java",
          "version": {
            "requires": "2025.0.0"
          }
        },
        {
          "group": "gov.nist.math",
          "module": "jama",
          "version": {
            "requires": "1.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "bearlib-2025.0.2.jar",
          "url": "bearlib-2025.0.2.jar",
          "size": 18836,
          "sha512": "79e5b45eaa5979ecfa6f84e1476ff9d1c299ddc2ff4cf4d5f1dc3f0a428881d24a156cca217d399220062ac27bff07cc2e815da4a3cb7ab00dab9ac3a0b3473d",
          "sha256": "7a4fdd2223ec2b51c9facda767a6c2ac1cab15e541627a0a8dead2fc20bb40eb",
          "sha1": "3585039616268f9f995ffde92557524e865cff14",
          "md5": "a80d97f932ef08f02161663805f718c6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "bearlib-2025.0.2-sources.jar",
          "url": "bearlib-2025.0.2-sources.jar",
          "size": 15116,
          "sha512": "7defb754c719b1ba7269132a0942b69a8da68196e0c9aee2616de932b61e2af5d0bbfb5e936b543f1614ece0ef50f21515c4c98c13d55299dd7b8b16eba766c5",
          "sha256": "315ad0432f83f0cee1b8445f05347e4786fed116b02e48c1e4e076c91f47baf9",
          "sha1": "1066424157cb75e0a491643d9568ea99521965db",
          "md5": "c9dd4a86d1d912f0bc46b12193ae12a3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "bearlib-2025.0.2-javadoc.jar",
          "url": "bearlib-2025.0.2-javadoc.jar",
          "size": 154456,
          "sha512": "51115f4ea58a11223dc4431ac1783dc6fc15aed74b7af442cc9af4821059e153afcfa8938e6420152732e3febc2cb019149fecc9def3811dbea60cc2684318bb",
          "sha256": "f958760a0aaf6ee7a501ebe9b4c467bffc59938b22b5a69a0ae2a28b1a6b0f3b",
          "sha1": "8e21349dd92d615796199505eae04b442dea886f",
          "md5": "846a466e26ed64fa5031535b5489f96b"
        }
      ]
    }
  ]
}
