{
  "formatVersion": "1.1",
  "component": {
    "group": "frc4068.bearlib",
    "module": "bearlib",
    "version": "2025.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "bearlib-2025.3.1.jar",
          "url": "bearlib-2025.3.1.jar",
          "size": 43505,
          "sha512": "462733975adbea1273cbc47835a38184a2832d3b064f7703d63d7ba790b1d2f03f680b0f9ba7f419f5991765f3a26c713a500c7338d2dbf91ed77c5fd8f107d3",
          "sha256": "683bac2f12f4840baa5a636548d1f33e5f7d4f728971ba0f561a7b5589cfcc08",
          "sha1": "1eee37e61896257bc94f72e5519059253d65988d",
          "md5": "5d44b67a31085992082eb9579cf9bc52"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2025.3.1"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2025.3.1"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2025.3.1"
          }
        },
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2025.3.1"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2025.3.1"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2025.3.1"
          }
        },
        {
          "group": "edu.wpi.first.wpinet",
          "module": "wpinet-java",
          "version": {
            "requires": "2025.3.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2025.3.1"
          }
        },
        {
          "group": "edu.wpi.first.apriltag",
          "module": "apriltag-java",
          "version": {
            "requires": "2025.3.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiunits",
          "module": "wpiunits-java",
          "version": {
            "requires": "2025.3.1"
          }
        },
        {
          "group": "edu.wpi.first.epilogue",
          "module": "epilogue-runtime-java",
          "version": {
            "requires": "2025.3.1"
          }
        },
        {
          "group": "edu.wpi.first.thirdparty.frc2025.opencv",
          "module": "opencv-java",
          "version": {
            "requires": "4.10.0-3"
          }
        },
        {
          "group": "org.ejml",
          "module": "ejml-simple",
          "version": {
            "requires": "0.43.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.15.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.15.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.15.2"
          }
        },
        {
          "group": "us.hebi.quickbuf",
          "module": "quickbuf-runtime",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "edu.wpi.first.wpilibNewCommands",
          "module": "wpilibNewCommands-java",
          "version": {
            "requires": "2025.3.1"
          }
        },
        {
          "group": "com.revrobotics.frc",
          "module": "REVLib-java",
          "version": {
            "requires": "2025.0.2"
          }
        },
        {
          "group": "gov.nist.math",
          "module": "jama",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.18.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jdk8",
          "version": {
            "requires": "2.15.2"
          }
        }
      ],
      "files": [
        {
          "name": "bearlib-2025.3.1.jar",
          "url": "bearlib-2025.3.1.jar",
          "size": 43505,
          "sha512": "462733975adbea1273cbc47835a38184a2832d3b064f7703d63d7ba790b1d2f03f680b0f9ba7f419f5991765f3a26c713a500c7338d2dbf91ed77c5fd8f107d3",
          "sha256": "683bac2f12f4840baa5a636548d1f33e5f7d4f728971ba0f561a7b5589cfcc08",
          "sha1": "1eee37e61896257bc94f72e5519059253d65988d",
          "md5": "5d44b67a31085992082eb9579cf9bc52"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "bearlib-2025.3.1-sources.jar",
          "url": "bearlib-2025.3.1-sources.jar",
          "size": 31651,
          "sha512": "b9ee25edc0b8d5f087a3723ad1432dde3c5cd232a5b72cd8a3e22336af3f21f2139813f0073e58f7174025705d248c98911a7fc51e9f728628c41f68552f8b64",
          "sha256": "75b30be8b51fd40ab2535bf358e835b61cfc9d9e6dca6d2ee48b24f415f8862c",
          "sha1": "a3ed609759de0589cf85b886f16ee2a99c8a8b75",
          "md5": "8f261f26c771c36b4a5a5b2422e56504"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "bearlib-2025.3.1-javadoc.jar",
          "url": "bearlib-2025.3.1-javadoc.jar",
          "size": 230253,
          "sha512": "30f2edcc98ab2969a9e415877cdcd81d89f57b28ce29b11afb2e491e439018d91db3dd2f7195822fc11034d36a6c09747b61b4f86fd7daecb5fe9aa19ec307ba",
          "sha256": "6579d2cc30382e1bd4aa42c8508d969ae69f686a48ca7ff5a3555d3371fe146b",
          "sha1": "f1f0f7cbffbafcf14fe16f32e4b302dc87ce26a9",
          "md5": "8a54412332290aba75675fa8003e29f0"
        }
      ]
    }
  ]
}
