{
  "formatVersion": "1.1",
  "component": {
    "group": "frc4068.bearlib",
    "module": "bearlib",
    "version": "2025.2.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "bearlib-2025.2.4.jar",
          "url": "bearlib-2025.2.4.jar",
          "size": 40120,
          "sha512": "cef99a6b1a9fa8f2d61e3ad95c48f5ced92a1b4c93fcb2851ae725b7a0f4b86cd4eaf7cfaa7d8b9df2807127155ca9f89ad43fbbfc7e380395d714447d8ae227",
          "sha256": "40d5d6a50824fd05b2765dcfe3cd0b019ab3eba36bb781e93db66dbab0d6122a",
          "sha1": "1f4b2dd355011bcb6b2740896b34ccf908e4f433",
          "md5": "e0a6b9c9e8fd34905e8242c7f64fc80c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2025.3.1"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2025.3.1"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2025.3.1"
          }
        },
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2025.3.1"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2025.3.1"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2025.3.1"
          }
        },
        {
          "group": "edu.wpi.first.wpinet",
          "module": "wpinet-java",
          "version": {
            "requires": "2025.3.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2025.3.1"
          }
        },
        {
          "group": "edu.wpi.first.apriltag",
          "module": "apriltag-java",
          "version": {
            "requires": "2025.3.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiunits",
          "module": "wpiunits-java",
          "version": {
            "requires": "2025.3.1"
          }
        },
        {
          "group": "edu.wpi.first.epilogue",
          "module": "epilogue-runtime-java",
          "version": {
            "requires": "2025.3.1"
          }
        },
        {
          "group": "edu.wpi.first.thirdparty.frc2025.opencv",
          "module": "opencv-java",
          "version": {
            "requires": "4.10.0-3"
          }
        },
        {
          "group": "org.ejml",
          "module": "ejml-simple",
          "version": {
            "requires": "0.43.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.15.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.15.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.15.2"
          }
        },
        {
          "group": "us.hebi.quickbuf",
          "module": "quickbuf-runtime",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "edu.wpi.first.wpilibNewCommands",
          "module": "wpilibNewCommands-java",
          "version": {
            "requires": "2025.3.1"
          }
        },
        {
          "group": "com.revrobotics.frc",
          "module": "REVLib-java",
          "version": {
            "requires": "2025.0.2"
          }
        },
        {
          "group": "gov.nist.math",
          "module": "jama",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.18.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jdk8",
          "version": {
            "requires": "2.15.2"
          }
        }
      ],
      "files": [
        {
          "name": "bearlib-2025.2.4.jar",
          "url": "bearlib-2025.2.4.jar",
          "size": 40120,
          "sha512": "cef99a6b1a9fa8f2d61e3ad95c48f5ced92a1b4c93fcb2851ae725b7a0f4b86cd4eaf7cfaa7d8b9df2807127155ca9f89ad43fbbfc7e380395d714447d8ae227",
          "sha256": "40d5d6a50824fd05b2765dcfe3cd0b019ab3eba36bb781e93db66dbab0d6122a",
          "sha1": "1f4b2dd355011bcb6b2740896b34ccf908e4f433",
          "md5": "e0a6b9c9e8fd34905e8242c7f64fc80c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "bearlib-2025.2.4-sources.jar",
          "url": "bearlib-2025.2.4-sources.jar",
          "size": 29341,
          "sha512": "66c99270ad52fc236cd80fba94f24c6eb8b4e58b18a992cfd901f7a181a0d13ab77c3effcb73da252f080a817ab94418ed1497cb5f96894757252515037ab8a9",
          "sha256": "5fdc1fc810411c4537cda8f54b07f45ba00f9ba2fa10ec94dbf3020d9ab7996e",
          "sha1": "aa3d7298de59982ef0169697420681ecf27d3a2d",
          "md5": "be4cf5bffe66c5b3fa19af20222bcb89"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "bearlib-2025.2.4-javadoc.jar",
          "url": "bearlib-2025.2.4-javadoc.jar",
          "size": 227088,
          "sha512": "188761ca81ca4acbb49ac0c77dc1e0dfb537824f46e9603933c05da0cc783fdf520403d9c061c055b3cc4ad5aee631fa3fd77d73918bf9a682453fb7a333cdc3",
          "sha256": "4ea4e494082aad011a596ebcce8848af13c7c4f4f399b703e74530a20259811c",
          "sha1": "fdfcd488aafbf00f989e5e6981eb37f796e82400",
          "md5": "5f9253e3262d14201508650c7cb906e3"
        }
      ]
    }
  ]
}
