{
  "formatVersion": "1.1",
  "component": {
    "group": "frc4068.bearlib",
    "module": "bearlib",
    "version": "2025.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "bearlib-2025.1.2.jar",
          "url": "bearlib-2025.1.2.jar",
          "size": 38828,
          "sha512": "d249ffafbe54a7d7e809cf84bea0131566374fd657224341bd26c1eee364807b94887761d9387e10b70450df6a6e2451c003c274b6c79b3ee35f71d6f632ab68",
          "sha256": "d0fef71749ee553958a2e7b1d26f8797415af3be79d98938a2c684a5da30c798",
          "sha1": "19e2f407bb9609068b3e89a651bda4b463cd150c",
          "md5": "ecc488b97a0c7f153f493d4e9437db56"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2025.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2025.1.1"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2025.1.1"
          }
        },
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2025.1.1"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2025.1.1"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2025.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpinet",
          "module": "wpinet-java",
          "version": {
            "requires": "2025.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2025.1.1"
          }
        },
        {
          "group": "edu.wpi.first.apriltag",
          "module": "apriltag-java",
          "version": {
            "requires": "2025.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiunits",
          "module": "wpiunits-java",
          "version": {
            "requires": "2025.1.1"
          }
        },
        {
          "group": "edu.wpi.first.epilogue",
          "module": "epilogue-runtime-java",
          "version": {
            "requires": "2025.1.1"
          }
        },
        {
          "group": "edu.wpi.first.thirdparty.frc2025.opencv",
          "module": "opencv-java",
          "version": {
            "requires": "4.10.0-3"
          }
        },
        {
          "group": "org.ejml",
          "module": "ejml-simple",
          "version": {
            "requires": "0.43.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.15.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.15.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.15.2"
          }
        },
        {
          "group": "us.hebi.quickbuf",
          "module": "quickbuf-runtime",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "edu.wpi.first.wpilibNewCommands",
          "module": "wpilibNewCommands-java",
          "version": {
            "requires": "2025.1.1"
          }
        },
        {
          "group": "com.revrobotics.frc",
          "module": "REVLib-java",
          "version": {
            "requires": "2025.0.0"
          }
        },
        {
          "group": "gov.nist.math",
          "module": "jama",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.18.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jdk8",
          "version": {
            "requires": "2.15.2"
          }
        }
      ],
      "files": [
        {
          "name": "bearlib-2025.1.2.jar",
          "url": "bearlib-2025.1.2.jar",
          "size": 38828,
          "sha512": "d249ffafbe54a7d7e809cf84bea0131566374fd657224341bd26c1eee364807b94887761d9387e10b70450df6a6e2451c003c274b6c79b3ee35f71d6f632ab68",
          "sha256": "d0fef71749ee553958a2e7b1d26f8797415af3be79d98938a2c684a5da30c798",
          "sha1": "19e2f407bb9609068b3e89a651bda4b463cd150c",
          "md5": "ecc488b97a0c7f153f493d4e9437db56"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "bearlib-2025.1.2-sources.jar",
          "url": "bearlib-2025.1.2-sources.jar",
          "size": 28010,
          "sha512": "ff849549ab7e6e788d0d5fe191975cc77afb59974d1024cc9b3e6e984db039894aebedb19712ee2886cb004755a5de8ab301a061767d51dfe45fd17a31a2a6bf",
          "sha256": "4844c18be4f912ba08d3c5ae9c9f5d55442c6c91c572df7feea8763d1f43f129",
          "sha1": "d9d1dfc14043cdf2b8cc5444ffc61d71f9e42c04",
          "md5": "ac70f0aab5178e3674d04628afee594b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "bearlib-2025.1.2-javadoc.jar",
          "url": "bearlib-2025.1.2-javadoc.jar",
          "size": 223875,
          "sha512": "85b19158d316b5985a123d1b53c2aba02a3232a97323d03e6d45727aa2e64c245952880d57aca458de16e513daec205d1b4eecb6821776249a84d2e778478e5b",
          "sha256": "922ad58b417ebed6ae02312d88fb3819eda208c200d389908b90829a65292bb0",
          "sha1": "6eeeee65c567c7bc5854263ae717ee30771f8af3",
          "md5": "701786ceb953e537750ee837d79061d6"
        }
      ]
    }
  ]
}
